spring:
  elasticsearch:
    rest:
      uris: http://10.10.72.168:9200
  redis:
    host: 10.10.0.250 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: Fl3CVxWS # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 200ms # 连接超时时间（毫秒）
  rabbitmq:
    host: 10.10.86.205
    port: 5672
    #virtual-host: /mall
    username: admin
    password: admin
    publisher-confirms: true #如果对异步消息需要回调必须设置为true
  datasource:
    url: jdbc:mysql://10.10.110.106:3306/reader?useUnicode=true&characterEncoding=utf-8
    username: root
    password: f1Jq3kWI
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数


  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 10.10.72.168:9300
      cluster-name: es-book

logging:
  path: /var/logs #配置日志生成路径
